# Generated by Django 3.2.5 on 2021-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
